### PR TITLE
Add qpoases python interface

### PR DESCRIPTION
**Pull request by fabinsch**
Hello, I would like to add the python interface to the conda-forge package of qpoases. Currently, only the c++ package is built but not the python interface. I needed to apply a minor patch to make it build.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Hi @fabinsh, thanks a lot. Just a curiosity, did you checked if the generated Python bindings .so is linking the libqpOASES.so library compiled by CMake or embeedding the symbols directly in  the enerated Python bindings .so ? Linking the  libqpOASES.so library compiled by CMake would be better, but not compulsory from my point of view to merge the PR.

**Comment by fabinsch** [comment]
Hi @traversaro , when I edited the recipe and tried out the build locally I added some echos and I could see the following after building the bindings:

```
ldd qpoases.cpython-38-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffc3c7fc000)
	libqpOASES.so.3.2 => $PREFIX/lib/libqpOASES.so.3.2 (0x00007fee8853b000)
	libstdc++.so.6 => $PREFIX/lib/libstdc++.so.6 (0x00007fee88233000)
	libgcc_s.so.1 => $PREFIX/lib/libgcc_s.so.1 (0x00007fee88521000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fee87e65000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fee87b63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fee883e7000)
```
So I think it should be fine.

**Comment by traversaro** [comment]
Great! Another nice to have would be to split the C++ and Python parts in two different outputs with qpoases being a metapackages that installs both of them (example of recipe of this kind: https://github.com/conda-forge/gz-math-feedstock/tree/main/recipe), but the better is enemy of the good, so we can merge this as soon as the CI is green, and open an issue for the multi-output stuff.

**Comment by fabinsch** [comment]
> Great! Another nice to have would be to split the C++ and Python parts in two different outputs with qpoases being a metapackages that installs both of them (example of recipe of this kind: https://github.com/conda-forge/gz-math-feedstock/tree/main/recipe), but the better is enemy of the good, so we can merge this as soon as the CI is green, and open an issue for the multi-output stuff.

Okay, I see. Currently, I am trying to make it work for macOS and windows. In qpOASES they have a specific makefile for every os (defining os-specific linking flags etc). In contrast, the `CMakeLists.txt` seems to not be making these differences. Do you remember if there is a specific reason for which you decided to use the CMake way to build instead of going with the makefile?

**Comment by traversaro** [comment]
> > Great! Another nice to have would be to split the C++ and Python parts in two different outputs with qpoases being a metapackages that installs both of them (example of recipe of this kind: https://github.com/conda-forge/gz-math-feedstock/tree/main/recipe), but the better is enemy of the good, so we can merge this as soon as the CI is green, and open an issue for the multi-output stuff.
> 
> Okay, I see. Currently, I am trying to make it work for macOS and windows. In qpOASES they have a specific makefile for every os (defining os-specific linking flags etc). In contrast, the `CMakeLists.txt` seems to not be making these differences. 

Consider that `CMakeLists.txt` also have different os-specific default compilation options, and similarly conda-forge also sets environment variables with different os-specific compilation options. So even if the CMake does not contain os-specific logic, the resulting compilation options on the different OSs will be different.

> Do you remember if there is a specific reason for which you decided to use the CMake way to build instead of going with the makefile?

As the upstream offered both CMake and manually-written Makefiles, I opted for CMake because with CMake it is easier to support cases that the original author of the Makefile may not have originally considered, such as cross-compilation, compilation for PyPy or similar. Also compilation on Windows is tipically much easier when using CMake. With manually-written Makefiles, the specific targets are tipically not standardized: for example, I was not even sure the existing Makefiles had the `install` target.

In general, as we are currently compiling the C++ library with CMake, it is not trivial to switch to make, as the ABI may be changing in subtle ways when the build system changes (see https://conda-forge.org/docs/maintainer/knowledge_base.html#moving-from-an-autotools-build-to-a-cmake-build).

**Comment by fabinsch** [comment]
Thanks for the detailed answer. I quickly [tried out the make option](https://github.com/conda-forge/qpoases-feedstock/pull/1/commits/5060f0919ad336e94f317a767f0e5fea2d8c921c), even though stuff like automatic install is missing currently, to see if it could help with the problems I'm facing on [macOS](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=612311&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=520) for example, but I get the same errors with Cmake or make (and make has more downsides to handle afterward).

So I will stick to CMake and try to fix these errors on mac and windows locally when installing the python bindings..

**Comment by fabinsch** [comment]
Importing qpoases in python is working for all three os. The last commit adds a step to run the python tests (working locally on my linux machine). We should be soon fine.

**Comment by traversaro** [comment]
I copied the tests over to the recipe directory to execute it, but it seems that there are a lot of references to C++ compiled examples in them, so probably we may want to drop them.

**Comment by fabinsch** [comment]
Yes I see. I was wondering, if we could also just execute the python_tests in the build.sh and bld.bat file after building the bindings..

**Comment by traversaro** [comment]
> Yes I see. I was wondering, if we could also just execute the python_tests in the build.sh and bld.bat file after building the bindings..

Sure, the problem is that I am not sure if we are building (and in the correct place) the C++ examples, and apparently those are necessary (see https://github.com/coin-or/qpOASES/blob/9bd3374a26d8e92e90eef1854228d73326dc90a2/interfaces/python/tests/test_examples.py#L42 and https://github.com/coin-or/qpOASES/blob/9bd3374a26d8e92e90eef1854228d73326dc90a2/interfaces/python/tests/test_examples.py#L94).

**Comment by fabinsch** [comment]
If I build qpoases locally on my machine I have the examples in `~/qpOASES/build/bin` -> see the end of this output here

```
(test_import) ➜  build git:(fix-python) ✗ cmake ${CMAKE_ARGS} -GNinja .. \                 
      -DCMAKE_BUILD_TYPE=Release \
      -DQPOASES_AVOID_LA_NAMING_CONFLICTS:BOOL=ON \
      -DBUILD_SHARED_LIBS:BOOL=ON \
      -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
      -DBUILD_TESTING:BOOL=ON ..
CMake Deprecation Warning at CMakeLists.txt:32 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The CXX compiler identification is Clang 12.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-12 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING


-- Build files have been written to: /home/fschramm/workspace/tmo/qpOASES/build
(test_import) ➜  build git:(fix-python) ✗ cmake --build . --config Release                 
[14/42] Building CXX object CMakeFiles/example1.dir/examples/example1.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example1.cpp:36:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[15/42] Building CXX object CMakeFiles/example1a.dir/examples/example1a.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example1a.cpp:36:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[16/42] Building CXX object CMakeFiles/example1b.dir/examples/example1b.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example1b.cpp:35:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[17/42] Building CXX object CMakeFiles/qpOASES.dir/src/SolutionAnalysis.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/src/SolutionAnalysis.cpp:37:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES/extras/SolutionAnalysis.hpp:41:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[18/42] Building CXX object CMakeFiles/example3.dir/examples/example3.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example3.cpp:39:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[19/42] Building CXX object CMakeFiles/example2.dir/examples/example2.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example2.cpp:37:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[20/42] Building CXX object CMakeFiles/example3b.dir/examples/example3b.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example3b.cpp:39:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[21/42] Building CXX object CMakeFiles/example4.dir/examples/example4.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example4.cpp:39:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[22/42] Building CXX object CMakeFiles/qrecipe.dir/examples/qrecipe.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/qrecipe.cpp:36:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[23/42] Building CXX object CMakeFiles/example5.dir/examples/example5.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/example5.cpp:39:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[24/42] Building CXX object CMakeFiles/exampleLP.dir/examples/exampleLP.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/exampleLP.cpp:36:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[25/42] Building CXX object CMakeFiles/qrecipeSchur.dir/examples/qrecipeSchur.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/examples/qrecipeSchur.cpp:37:
In file included from /home/fschramm/workspace/tmo/qpOASES/include/qpOASES.hpp:69:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
/home/fschramm/workspace/tmo/qpOASES/examples/qrecipeSchur.cpp:64:14: warning: declaration shadows a local variable [-Wshadow]
    for (int i = 0; i < NV; i++)
             ^
/home/fschramm/workspace/tmo/qpOASES/examples/qrecipeSchur.cpp:47:7: note: previous declaration is here
        long i;
             ^
/home/fschramm/workspace/tmo/qpOASES/examples/qrecipeSchur.cpp:67:2: warning: misleading indentation; statement is not part of the previous 'for' [-Wmisleading-indentation]
        real_t* A_full = A->full();
        ^
/home/fschramm/workspace/tmo/qpOASES/examples/qrecipeSchur.cpp:64:5: note: previous statement is here
    for (int i = 0; i < NV; i++)
    ^
3 warnings generated.
[27/42] Building CXX object CMakeFiles/qpOASES.dir/src/SQProblemSchur.cpp.o
In file included from /home/fschramm/workspace/tmo/qpOASES/src/SQProblemSchur.cpp:37:
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/SQProblemSchur.hpp:141:23: warning: 'qpOASES::SQProblemSchur::setupAuxiliaryQP' hides overloaded virtual function [-Woverloaded-virtual]
                virtual returnValue setupAuxiliaryQP(   SymmetricMatrix *H_new,         /**< New Hessian matrix. \n
                                    ^
/home/fschramm/workspace/tmo/qpOASES/include/qpOASES/QProblem.hpp:849:23: note: hidden overloaded virtual function 'qpOASES::QProblem::setupAuxiliaryQP' declared here: different number of parameters (2 vs 6)
                virtual returnValue setupAuxiliaryQP(   const Bounds* const guessedBounds,                      /**< Initial guess for working set of bounds. */
                                    ^
1 warning generated.
[42/42] Linking CXX executable bin/example1b
(test_import) ➜  build git:(fix-python) ✗ cmake --build . --config Release --target install
[0/1] Install the project...
-- Install configuration: "Release"
-- Installing: /home/fschramm/anaconda3/envs/test_import/lib/libqpOASES.so.3.2
-- Set runtime path of "/home/fschramm/anaconda3/envs/test_import/lib/libqpOASES.so.3.2" to "/home/fschramm/anaconda3/envs/test_import/lib:/home/fschramm/anaconda3/envs/test_import/lib/casadi"
-- Up-to-date: /home/fschramm/anaconda3/envs/test_import/lib/libqpOASES.so
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES.hpp
-- Up-to-date: /home/fschramm/anaconda3/envs/test_import/include/qpOASES
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SQProblemSchur.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Bounds.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Options.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SubjectTo.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Utils.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/QProblemB.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/QProblem.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Constraints.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/MessageHandling.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SQProblem.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Matrices.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Constants.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SubjectTo.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/UnitTesting.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/MessageHandling.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Indexlist.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SQProblemSchur.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Types.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SparseSolver.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Bounds.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/SQProblem.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/LapackBlasReplacement.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Indexlist.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Constraints.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Flipper.hpp
-- Up-to-date: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/extras
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/extras/SolutionAnalysis.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/extras/SolutionAnalysis.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/extras/OQPinterface.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/QProblem.ipp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/QProblemB.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/Utils.hpp
-- Installing: /home/fschramm/anaconda3/envs/test_import/include/qpOASES/ConstraintProduct.hpp
(test_import) ➜  build git:(fix-python) ✗ l
total 144K
drwxr-xr-x  5 fschramm willow 4.0K Nov 15 23:01 .
drwxr-xr-x 14 fschramm willow 4.0K Nov 15 23:00 ..
drwxr-xr-x  2 fschramm willow 4.0K Nov 15 23:01 bin
-rw-r--r--  1 fschramm willow  53K Nov 15 23:00 build.ninja
-rw-r--r--  1 fschramm willow  13K Nov 15 23:00 CMakeCache.txt
drwxr-xr-x 17 fschramm willow 4.0K Nov 15 23:00 CMakeFiles
-rw-r--r--  1 fschramm willow 4.7K Nov 15 23:00 cmake_install.cmake
-rw-r--r--  1 fschramm willow 2.5K Nov 15 23:01 install_manifest.txt
drwxr-xr-x  2 fschramm willow 4.0K Nov 15 23:01 libs
-rw-r--r--  1 fschramm willow  35K Nov 15 23:01 .ninja_deps
-rw-r--r--  1 fschramm willow 3.5K Nov 15 23:01 .ninja_log
(test_import) ➜  build git:(fix-python) ✗ l bin 
total 516K
drwxr-xr-x 2 fschramm willow 4.0K Nov 15 23:01 .
drwxr-xr-x 5 fschramm willow 4.0K Nov 15 23:01 ..
-rwxr-xr-x 1 fschramm willow  43K Nov 15 23:01 example1
-rwxr-xr-x 1 fschramm willow  35K Nov 15 23:01 example1a
-rwxr-xr-x 1 fschramm willow  43K Nov 15 23:01 example1b
-rwxr-xr-x 1 fschramm willow  43K Nov 15 23:01 example2
-rwxr-xr-x 1 fschramm willow  42K Nov 15 23:01 example3
-rwxr-xr-x 1 fschramm willow  42K Nov 15 23:01 example3b
-rwxr-xr-x 1 fschramm willow  40K Nov 15 23:01 example4
-rwxr-xr-x 1 fschramm willow  43K Nov 15 23:01 example5
-rwxr-xr-x 1 fschramm willow  43K Nov 15 23:01 exampleLP
-rwxr-xr-x 1 fschramm willow  57K Nov 15 23:01 qrecipe
-rwxr-xr-x 1 fschramm willow  62K Nov 15 23:01 qrecipeSchur
(test_import) ➜  build git:(fix-python) ✗ cd bin
(test_import) ➜  bin git:(fix-python) ✗ pwd
/home/fschramm/workspace/tmo/qpOASES/build/bin

```

**Comment by fabinsch** [comment]
I think we could either patch l.48 in test_examples to match this build/bin directory (if we execute in build.sh or bld.bat) or we copy them also to the correct places to execute the tests in the meta.yml. We need example1, example1b and example2.

**Comment by traversaro** [comment]
> If I build qpoases locally on my machine I have the examples in `~/qpOASES/build/bin` -> see the end of this output here

Ah cool, I missed that!

**Comment by traversaro** [comment]
If you want to carry over files for the tests, you need also to list them (even just the containing directory) in the files attribute under test, see https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#test-files .

**Comment by fabinsch** [comment]
I could successfully copy to files for testing (a isFile call in the python_examples confirms that) but the examples are no longer linked to the qpoases library (therefor the popen fails). Running in the meta.yml test section I can see the following (see my last commit):
```
+ ldd build/bin/example1
	linux-vdso.so.1 =>  (0x00007ffe037a1000)
	libqpOASES.so.3.2 => not found
	libstdc++.so.6 => /home/conda/feedstock_root/build_artifacts/qpoases_1668584253246/_build_env/lib/libstdc++.so.6 (0x00007f359a4a5000)
	libgcc_s.so.1 => /home/conda/feedstock_root/build_artifacts/qpoases_1668584253246/_build_env/lib/libgcc_s.so.1 (0x00007f359a48c000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f359a075000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3599d73000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f359a443000)
```

**Comment by fabinsch** [comment]
Directly after doing the cmake (before the bindings, copying etc), if I check what the build/bin/example1 is linked against I can see:
```
	linux-vdso.so.1 =>  (0x00007ffcc2382000)
	libqpOASES.so.3.2 => $PREFIX/lib/libqpOASES.so.3.2 (0x00007f9baf4be000)
	libstdc++.so.6 => $PREFIX/lib/libstdc++.so.6 (0x00007f9baf167000)
	libgcc_s.so.1 => $PREFIX/lib/libgcc_s.so.1 (0x00007f9baf4a4000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9baed99000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9baea97000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9baf31b000)
```

**Comment by fabinsch** [comment]
After discussing with @jcarpent, we think it's enough, for now, to test the import in python of qpoases bindings and we can drop running the test_examples.py.

**Review by jcarpent — APPROVED** [review]
Very nice work @fabinsch.
Thanks a lot. And thanks to @traversaro for the nice feedback.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @fabinsch  @jcarpent !

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@Tobias-Fischer once this is merged, probably we can enable `qpoases` on qpsolvers.

**Pull request merged**
